import Link from 'next/link';
import { Check, ShieldCheck } from 'lucide-react';

export const metadata = { title: 'Plans' };

const plans=[
  {name:'Patient',price:'Free',copy:'Your personal Dokta account.',items:['Appointments','Health records','Medication record','Prescription status'],cta:'Create account',href:'/signup'},
  {name:'Practitioner',price:'R499',period:'/ month',copy:'For independent healthcare practitioners.',items:['Doctor workspace','Consultations','e-Prescribing','Clinical tools'],cta:'Provider access',href:'/login?role=doctor'},
  {name:'Pharmacy',price:'R1,499',period:'/ month',copy:'For connected dispensing teams.',items:['Prescription queue','Inventory','Point of sale','Pharmacy reporting'],cta:'Pharmacy access',href:'/login?role=pharmacy'},
  {name:'Clinic',price:'R1,999',period:'/ month',copy:'For multi-user care facilities.',items:['Clinic queue','Care-team workflows','Operational workspace','Role-based access'],cta:'Contact Dokta',href:'/contact'},
];
export default function Pricing(){return <main id="main" className="min-h-dvh bg-[#f4f8fb] text-[#061d35]"><header className="bg-[linear-gradient(135deg,#041a2e,#064e4b)] text-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-4 py-5 sm:px-6 lg:px-8"><Link href="/" className="font-display text-xl font-bold">DOKTA</Link><Link href="/login" className="rounded-xl border border-white/15 bg-white/10 px-4 py-2 text-sm font-semibold">Sign in</Link></div><div className="mx-auto max-w-3xl px-4 pb-16 pt-10 text-center sm:px-6"><ShieldCheck className="mx-auto h-7 w-7 text-emerald-300"/><h1 className="mt-5 font-display text-4xl font-bold sm:text-5xl">Dokta plans</h1><p className="mt-3 text-white/55">Choose the workspace that fits your healthcare operation.</p></div></header><section className="mx-auto grid max-w-7xl gap-4 px-4 py-10 sm:grid-cols-2 sm:px-6 lg:grid-cols-4 lg:px-8">{plans.map(p=><article key={p.name} className="flex flex-col rounded-[1.5rem] border border-white bg-white p-5 shadow-xl shadow-slate-900/[.05]"><p className="text-sm font-semibold text-emerald-600">{p.name}</p><p className="mt-4 font-display text-3xl font-bold">{p.price}<span className="text-xs font-medium text-slate-400">{p.period}</span></p><p className="mt-2 min-h-10 text-sm text-slate-500">{p.copy}</p><ul className="mt-6 flex-1 space-y-3">{p.items.map(i=><li key={i} className="flex gap-2 text-sm"><Check className="h-4 w-4 shrink-0 text-emerald-500"/>{i}</li>)}</ul><Link href={p.href} className="mt-7 flex min-h-11 items-center justify-center rounded-xl bg-[#082f4e] px-4 text-sm font-bold text-white">{p.cta}</Link></article>)}</section><p className="mx-auto max-w-3xl px-4 pb-12 text-center text-xs text-slate-400">Provider access is subject to verification. Subscription billing must be activated before paid plans are sold.</p></main>}